version: '3'
services:
  test_zookeeper:
    image: wurstmeister/zookeeper
    container_name: test_zookeeper
    restart: always
    ports:
      - 2181:2181

  test_kafka:
    image: wurstmeister/kafka
    container_name: test_kafka
    restart: always
    ports:
      - 9092:9092
    depends_on:
      - test_zookeeper
    links:
      - test_zookeeper:test_zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: test_zookeeper:2181
