spring:
  cloud:
    stream:
      bindings:
        helloOutput: #채널 이름
          destination: hello #queue 이름
          content-type: application/json

        dingDongOutput: #채널 이름
          destination: dingDong #queue 이름
          content-type: application/json

        output: #기본 채널 이름
          destination: hola #queue 이름
          content-type: application/json
      kafka:
        binder:
          brokers: localhost
server:
  port: 8081

logging:
  level:
    net.jogeum: DEBUG