spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      bindings:
        helloChannel: #채널 이름
          destination: hello #queue 이름
          content-type: application/json
          group: helloGroup #group 이름

        dingDongChannel: #채널 이름
          destination: dingDong #queue 이름
          content-type: application/json
          group: dingDongGroup #group 이름

        input: #기본 채널 이름
          destination: hola #queue 이름
          content-type: application/json
          group: holaGroup #group 이름
      kafka:
        binder:
          brokers: localhost

server:
  port: 8082

logging:
  level:
    net.jogeum: DEBUG