spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      bindings:
        helloChannel: #채널 이름
          destination: sayHello #queue 이름
          content-type: application/json
          group: helloGroup #group 이름

        bellChannel: #채널 이름
          destination: dingDong #queue 이름
          content-type: application/json
          group: bellGroup #group 이름
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost

server:
  port: 8082

logging:
  level:
    net.jogeum: DEBUG